name: Generate Team Snakes

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: fraserbrownirl
          outputs: |
            dist/fraser-snake.svg
            dist/fraser-snake-dark.svg?palette=github-dark&color_snake=1f6feb
      
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: eirlis
          outputs: |
            dist/eirlis-snake.svg
            dist/eirlis-snake-dark.svg?palette=github-dark&color_snake=7c3aed
      
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jeefxM
          outputs: |
            dist/jeef-snake.svg
            dist/jeef-snake-dark.svg?palette=github-dark&color_snake=059669
          
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
